# Project
site_name: 'Branch documentation'
site_description: 'Branch documentation for mobile deep linking'
site_author: 'Branch'
site_url: 'https://docs.branch.io'
repo_name: 'Branch documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/src/'
copyright: 'Copyright &copy; 2018 <a href="https://branch.io">Branch</a>'

# Files
theme:
  name: 'material'
  custom_dir: 'lib/mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature: false
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/router.js'
  - 'js/events.js'
  - 'js/modals.js'
  - 'js/images.js'
  - 'js/buttons.js'
  - 'js/progress.js'
  - 'js/tabs.js'
  - 'js/languages.js'
  - 'js/utils.js'
  - 'js/main.js'

# Extensions
markdown_extensions:
  - admonition:
  - codehilite: #(linenums=true)
  - footnotes:
  - toc(permalink=true):
  - meta:
  - markdown.extensions.tables:
  - pymdownx.magiclink:
  - pymdownx.betterem:
  - pymdownx.tilde:
  - pymdownx.emoji:
  - pymdownx.tasklist:
  - pymdownx.superfences:
  - attr_list:
  - markdown_include.include:
      base_path: src/includes/

# Options
extra:
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/branchmetrics/docs'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-docs'
  sources:
    mixpanel: '47ec8ea9ac102b1370221dcda476091c'
    google:
      optimize: 'GTM-PCPBXCN'
      analytics: 'UA-53307642-1'
    facebook: '1040694199304729'
    munchkin: '315-FTT-121'
    linkedin: '21211'
    bizible: true
    algolia:
      key: '887017d17a2c1e9490ad2c44caa7e817'
      index: 'branchmetrics'
      selector: '#algolia-doc-search'
      debug: true
      hits: 15
  nav_header:
    - index: 2
      title: Basic integration
    - index: 7
      title: Basic usage
    - index: 9
      title: Advanced usage
    - index: 18
      title: Resources
  nav_hidden: 'Hidden'
  is_visible:
    footer_floater_beta: false
    footer_floater_old_docs: false
    footer_nav: false
    header_git: false
    header_breadcrumb: true

# Pages
pages:
  - Getting started: index.md
  - Configure your dashboard: pages/dashboard/integrate.md
  - Configure your app:
    - iOS: pages/apps/ios.md
    - Android: pages/apps/android.md
    - Cordova PhoneGap Ionic: pages/apps/cordova-phonegap-ionic.md
    - mParticle Android: pages/apps/mparticle-android.md
    - mParticle iOS: pages/apps/mparticle-ios.md
    - Titanium: pages/apps/titanium.md
    - React Native: pages/apps/react-native.md
    - Unity: pages/apps/unity.md
    - Xamarin: pages/apps/xamarin.md
    - API: pages/apps/api.md
  - Configure your deep linking:
    - iOS Universal Links: pages/deep-linking/universal-links.md
    - Android App Links: pages/deep-linking/android-app-links.md
    - In-app deep link routing: pages/deep-linking/routing.md
  - Launch your app:
    - Apple App Store: pages/apps/ios-launch.md
    - Google Play: pages/apps/android-launch.md
  - Configure your website: pages/web/integrate.md
  - Create deep links: pages/links/integrate.md
  - Track analytics:
    - Dashboard analytics: pages/dashboard/analytics.md
    - New Dashboard Analytics: pages/dashboard/people-based-attribution.md
    - Liveview: pages/exports/pba-liveview.md
    - Time zone support: pages/dashboard/timezone.md
  - Links on your website:
    - Deepviews: pages/web/deep-views.md
    - Journeys App Banners: pages/web/journeys.md
    - AMP Journeys: pages/web/amp-journeys.md
    - Text Me The App: pages/web/text-me-the-app.md
    - Hosted Deep Link Data: pages/web/hosted-data.md
  - Links in your paid ads:
    - Universal Ads Partners: pages/deep-linked-ads/ad-networks-list.md
    - Branch Universal Ads: pages/deep-linked-ads/branch-universal-ads-mobile-tracking.md
    - A4G: pages/deep-linked-ads/a4g-mobile-tracking.md
    - Actionpay: pages/deep-linked-ads/actionpay-mobile-tracking.md
    - Ad4Screen: pages/deep-linked-ads/ad4screen-mobile-tracking.md
    - Adaction Interactive: pages/deep-linked-ads/adaction-interactive-mobile-tracking.md
    - Adacts Digital: pages/deep-linked-ads/adacts-digital-mobile-tracking.md
    - Adbloom: pages/deep-linked-ads/adbloom-mobile-tracking.md
    - Adcash: pages/deep-linked-ads/adcash-mobile-tracking.md
    - Adcolony: pages/deep-linked-ads/adcolony-mobile-tracking.md
    - Adcolony Performance Media: pages/deep-linked-ads/adcolony-performance-media-mobile-tracking.md
    - Adikteev: pages/deep-linked-ads/adikteev-mobile-tracking.md
    - Admitad: pages/deep-linked-ads/admitad-mobile-tracking.md
    - Admobs: pages/deep-linked-ads/admobs-mobile-tracking.md
    - Ads Army: pages/deep-linked-ads/ads-army-mobile-tracking.md
    - Ads Hero: pages/deep-linked-ads/ads-hero-mobile-tracking.md
    - Adsterra Network: pages/deep-linked-ads/adsterra-network-mobile-tracking.md
    - Adxperience: pages/deep-linked-ads/adxperience-mobile-tracking.md
    - Affise: pages/deep-linked-ads/affise-mobile-tracking.md
    - Affle: pages/deep-linked-ads/affle-mobile-tracking.md
    - App Samurai: pages/deep-linked-ads/app-samurai-mobile-tracking.md
    - Appier: pages/deep-linked-ads/appier-mobile-tracking.md
    - Apple Search: pages/deep-linked-ads/apple-mobile-tracking.md
    - Applift: pages/deep-linked-ads/applift-mobile-tracking.md
    - Applovin: pages/deep-linked-ads/applovin-mobile-tracking.md
    - Appnext: pages/deep-linked-ads/appnext-mobile-tracking.md
    - Art of Click: pages/deep-linked-ads/art-of-click-mobile-tracking.md
    - Avazu: pages/deep-linked-ads/avazu-mobile-tracking.md
    - Avow: pages/deep-linked-ads/avow-mobile-tracking.md
    - Awin: pages/deep-linked-ads/awin-mobile-tracking.md
    - Beintoo: pages/deep-linked-ads/beintoo-mobile-tracking.md
    - Billy Mobile: pages/deep-linked-ads/billy-mobile-mobile-tracking.md
    - Blind Ferret Incent: pages/deep-linked-ads/blind-ferret-incent-mobile-tracking.md
    - Blind Ferret Non-Incent: pages/deep-linked-ads/blind-ferret-non-incent-mobile-tracking.md
    - Centro: pages/deep-linked-ads/centro-mobile-tracking.md
    - CJ Affiliate: pages/deep-linked-ads/cj-affiliate-mobile-tracking.md
    - Claymotion: pages/deep-linked-ads/claymotion-mobile-tracking.md
    - Click2Commission: pages/deep-linked-ads/click2commission-mobile-tracking.md
    - Clickadu: pages/deep-linked-ads/clickadu-mobile-tracking.md
    - Clickky: pages/deep-linked-ads/clickky-mobile-tracking.md
    - Clinch: pages/deep-linked-ads/clinch-mobile-tracking.md
    - Connected Interactive: pages/deep-linked-ads/connected-interactive-mobile-tracking.md
    - Conversant Media: pages/deep-linked-ads/conversant-media-mobile-tracking.md
    - Criteo: pages/deep-linked-ads/criteo-mobile-tracking.md
    - crobo: pages/deep-linked-ads/crobo-mobile-tracking.md
    - CrossInstall: pages/deep-linked-ads/crossinstall-mobile-tracking.md
    - DataXu: pages/deep-linked-ads/dataxu-mobile-tracking.md
    - Digital Remedy: pages/deep-linked-ads/digital-remedy-mobile-tracking.md
    - Digital Turbine: pages/deep-linked-ads/digital-turbine-mobile-tracking.md
    - Display.io: pages/deep-linked-ads/display-io-mobile-tracking.md
    - Doozymob: pages/deep-linked-ads/doozymob-mobile-tracking.md
    - Doubleclick: pages/deep-linked-ads/doubleclick-mobile-tracking.md
    - Drawbridge: pages/deep-linked-ads/drawbridge-mobile-tracking.md
    - Espire: pages/deep-linked-ads/espire-mobile-tracking.md
    - Facebook: pages/deep-linked-ads/facebook-ads-overview.md
    - FeedMob: pages/deep-linked-ads/feedmob-mobile-tracking.md
    - Fyber: pages/deep-linked-ads/fyber-mobile-tracking.md
    - Gamespipe: pages/deep-linked-ads/gamespipe-mobile-tracking.md
    - GeistM: pages/deep-linked-ads/geistm-mobile-tracking.md
    - Getloyal: pages/deep-linked-ads/getloyal-mobile-tracking.md
    - Glispa: pages/deep-linked-ads/glispa-mobile-tracking.md
    - GlobalWide Media: pages/deep-linked-ads/globalwide-media-mobile-tracking.md
    - Google Adwords: pages/deep-linked-ads/google-ads-overview.md
    - Hybrid: pages/deep-linked-ads/hybrid-mobile-tracking.md
    - Impact Radius: pages/deep-linked-ads/impact-radius-mobile-tracking.md
    - Inflecto Media: pages/deep-linked-ads/inflecto-media-mobile-tracking.md
    - InMobi: pages/deep-linked-ads/inmobi-mobile-tracking.md
    - Instal: pages/deep-linked-ads/instal-mobile-tracking.md
    - IronSource: pages/deep-linked-ads/ironsource-mobile-tracking.md
    - Jampp: pages/deep-linked-ads/jampp-mobile-tracking.md
    - JetFuel Ads: pages/deep-linked-ads/jetfuel-ads-mobile-tracking.md
    - Kiip: pages/deep-linked-ads/kiip-mobile-tracking.md
    - Liftoff: pages/deep-linked-ads/liftoff-mobile-tracking.md
    - Magnet: pages/deep-linked-ads/magnet-mobile-tracking.md
    - Manage: pages/deep-linked-ads/manage-mobile-tracking.md
    - MediaMath: pages/deep-linked-ads/mediamath-mobile-tracking.md
    - Minimob: pages/deep-linked-ads/minimob-mobile-tracking.md
    - MobAir: pages/deep-linked-ads/mobair-mobile-tracking.md
    - Mobio: pages/deep-linked-ads/mobio-mobile-tracking.md
    - Mobobeat: pages/deep-linked-ads/mobobeat-mobile-tracking.md
    - MoBrain: pages/deep-linked-ads/mobrain-mobile-tracking.md
    - MobUpps: pages/deep-linked-ads/mobupps-mobile-tracking.md
    - Mobusi: pages/deep-linked-ads/mobusi-mobile-tracking.md
    - Mobvista: pages/deep-linked-ads/mobvista-mobile-tracking.md
    - MobX: pages/deep-linked-ads/mobx-mobile-tracking.md
    - Moloco: pages/deep-linked-ads/moloco-mobile-tracking.md
    - Motive: pages/deep-linked-ads/motive-mobile-tracking.md
    - Mozoo: pages/deep-linked-ads/mozoo-mobile-tracking.md
    - Mpire Network: pages/deep-linked-ads/mpire-network-mobile-tracking.md
    - MundoMedia: pages/deep-linked-ads/mundomedia-mobile-tracking.md
    - myTarget: pages/deep-linked-ads/mytarget-mobile-tracking.md
    - NativeX: pages/deep-linked-ads/nativex-mobile-tracking.md
    - Netcore Solutions: pages/deep-linked-ads/netcore-solutions-mobile-tracking.md
    - Oplytic: pages/deep-linked-ads/oplytic-mobile-tracking.md
    - Pepperjam: pages/deep-linked-ads/pepperjam-mobile-tracking.md
    - Performance Horizon: pages/deep-linked-ads/performance-horizon-mobile-tracking.md
    - Phunware: pages/deep-linked-ads/phunware-mobile-tracking.md
    - Picnic Media: pages/deep-linked-ads/picnic-media-mobile-tracking.md
    - Pinisight: pages/deep-linked-ads/pinisight-mobile-tracking.md
    - Pocketmath: pages/deep-linked-ads/pocketmath-mobile-tracking.md
    - Prappers: pages/deep-linked-ads/prappers-mobile-tracking.md
    - ProfiliAd: pages/deep-linked-ads/profiliad-mobile-tracking.md
    - Propeller Ads: pages/deep-linked-ads/propeller-ads-mobile-tracking.md
    - Quora: pages/deep-linked-ads/quora-mobile-tracking.md
    - RankMyApp: pages/deep-linked-ads/rankmyapp-mobile-tracking.md
    - Raykaad: pages/deep-linked-ads/raykaad-mobile-tracking.md
    - Remerge: pages/deep-linked-ads/remerge-mobile-tracking.md
    - RevX: pages/deep-linked-ads/revx-mobile-tracking.md
    - Sabio Mobile: pages/deep-linked-ads/sabio-mobile-mobile-tracking.md
    - ShopBack: pages/deep-linked-ads/shopback-mobile-tracking.md
    - Smadex: pages/deep-linked-ads/smadex-mobile-tracking.md
    - Sonarclick: pages/deep-linked-ads/sonarclick-mobile-tracking.md
    - Spyke Media: pages/deep-linked-ads/spyke-media-mobile-tracking.md
    - StackAdapt: pages/deep-linked-ads/stackadapt-mobile-tracking.md
    - StartApp: pages/deep-linked-ads/startapp-mobile-tracking.md
    - Str√∂er Mobile Performance: pages/deep-linked-ads/stroer-mobile-performance-mobile-tracking.md
    - TAB: pages/deep-linked-ads/tab-mobile-tracking.md
    - Taboola: pages/deep-linked-ads/taboola-mobile-tracking.md
    - Tapjoy: pages/deep-linked-ads/tapjoy-mobile-tracking.md
    - Tapsell: pages/deep-linked-ads/tapsell-mobile-tracking.md
    - Taptica: pages/deep-linked-ads/taptica-mobile-tracking.md
    - Teads: pages/deep-linked-ads/teads-mobile-tracking.md
    - The Trade Desk: pages/deep-linked-ads/the-trade-desk-mobile-tracking.md
    - Times Internet Limited: pages/deep-linked-ads/times-internet-limited-mobile-tracking.md
    - Twitter: pages/deep-linked-ads/twitter-mobile-tracking.md
    - Tyroo: pages/deep-linked-ads/tyroo-mobile-tracking.md
    - Unilead Network: pages/deep-linked-ads/unilead-network-mobile-tracking.md
    - Unity: pages/deep-linked-ads/unity-mobile-tracking.md
    - Ventes Avenues: pages/deep-linked-ads/ventes-avenues-mobile-tracking.md
    - Vishibility: pages/deep-linked-ads/vishibility-mobile-tracking.md
    - Vungle: pages/deep-linked-ads/vungle-mobile-tracking.md
    - Wakeapp: pages/deep-linked-ads/wakeapp-mobile-tracking.md
    - Yandex Direct: pages/deep-linked-ads/yandex-direct-mobile-tracking.md
    - YeahMobi: pages/deep-linked-ads/yeahmobi-mobile-tracking.md
    - YouAppi: pages/deep-linked-ads/youappi-mobile-tracking.md
    - YouAppi Retargeting: pages/deep-linked-ads/youappi-retargeting-mobile-tracking.md
    - Zorka Mobi: pages/deep-linked-ads/zorka-mobi-mobile-tracking.md
  - Links in your emails:
    - Email Partners: pages/emails/email-partners-list.md
    - Get Started: pages/emails/get-started.md
    - Adobe Campaign Standard: pages/emails/adobe-campaign-standard.md
    - Adobe Campaign Classic: pages/emails/adobe-campaign-classic.md
    - Amazon SES: pages/emails/amazon-ses.md
    - Betaout: pages/emails/betaout.md
    - Blueshift: pages/emails/blueshift.md
    - Braze (formerly Appboy): pages/emails/braze.md
    - Bronto: pages/emails/bronto.md
    - Campaign Monitor: pages/emails/campaign-monitor.md
    - Cheetah Digital Marketing Suite: pages/emails/cheetah-digital-marketing-suite.md
    - Oracle Eloqua: pages/emails/eloqua.md
    - Epsilon: pages/emails/epsilon.md
    - IBM Watson Campaign Automation: pages/emails/ibm_watson_campaign_automation.md
    - Iterable: pages/emails/iterable.md
    - Kahuna: pages/emails/kahuna.md
    - Klaviyo: pages/emails/klaviyo.md
    - Leanplum: pages/emails/leanplum.md
    - Mailgun: pages/emails/mailgun.md
    - Mailjet: pages/emails/mailjet.md
    - Mandrill: pages/emails/mandrill.md
    - MessageGears: pages/emails/messagegears.md
    - MoEngage: pages/emails/moengage.md
    - PostUp: pages/emails/postup.md
    - Rapidmail: pages/emails/rapidmail.md
    - Responsys: pages/emails/responsys.md
    - Sailthru: pages/emails/sailthru.md
    - Salesforce: pages/emails/salesforce.md
    - Selligent: pages/emails/selligent.md
    - Sender: pages/emails/sender.md
    - SendGrid: pages/emails/sendgrid.md
    - SparkPost: pages/emails/sparkpost.md
    - Vero: pages/emails/vero.md
    - Zeta: pages/emails/zeta.md
    - Support: pages/emails/support.md
    - Self Serve: pages/emails/self-serve.md
  - Links in push notifications: pages/advance/push-notifications.md
  - Links in organic search:
    - Firebase App Indexing: pages/organic-search/firebase.md
    - Spotlight Search: pages/organic-search/spotlight.md
    - General SEO Compatibility: pages/organic-search/branch-seo.md
  - Links for viral & referral:
    - Content sharing: pages/viral/content-sharing.md
    - Referral programs: pages/viral/referrals.md
  - Links in new app platforms:
    - Android Instant Apps: pages/app-to-app/android-instant-apps.md
    - iMessage Apps: pages/app-to-app/imessage-apps.md
  - Export Branch data:
    - Data Feeds:
      - Get Started: pages/exports/data-feeds.md
      - Data Integrations:
        - Get Started: pages/integrations/data-integrations.md
        - Adobe Analytics: pages/integrations/adobe-analytics.md
        - Adjust: pages/integrations/adjust.md
        - Amplitude: pages/integrations/amplitude.md
        - AppMetrica: pages/integrations/appmetrica.md
        - Braze: pages/integrations/appboy.md
        - Appsflyer: pages/integrations/appsflyer.md
        - CleverTap: pages/integrations/clevertap.md
        - Google Analytics: pages/integrations/google-analytics.md
        - Kochava: pages/integrations/kochava.md
        - Localytics: pages/integrations/localytics.md
        - Mixpanel: pages/integrations/mixpanel.md
        - mParticle: pages/integrations/mparticle.md
        - Segment: pages/integrations/segment.md
        - Tune: pages/integrations/tune.md
      - Data Export API: pages/exports/api-v3.md
      - Webhooks: pages/exports/ua-webhooks.md
      - Query API: pages/exports/query-api.md
      - Query Recipe Book: pages/exports/query-recipe-book.md
  - Branch Matching Overview: pages/resources/matching.md
  - Validation Tools: pages/resources/validation-tools.md
  - Case Studies and Infographics: pages/resources/case-studies.md
  - Hidden:
    - Google Search App Install Ads: pages/deep-linked-ads/google-search-install-ads.md
    - Google Search App Engagement Ads: pages/deep-linked-ads/google-search-engagement-ads.md
    - Google Display App Install Ads: pages/deep-linked-ads/google-display-install-ads.md
    - Google Display App Engagement Ads: pages/deep-linked-ads/google-display-engagement-ads.md
    - Google Universal App Campaigns: pages/deep-linked-ads/google-uac.md
    - Google Search Network Ads: pages/deep-linked-ads/google-xplatform-search-ads.md
    - Google Display Network Ads: pages/deep-linked-ads/google-xplatform-display-ads.md
    - Google Shopping Ads: pages/deep-linked-ads/google-shopping-ads.md
    - Google Adwords Conversion Setup: pages/deep-linked-ads/google-conversions.md
    - Google Video Ads: pages/deep-linked-ads/google-video-ads.md
    - Facebook App Install Ads: pages/deep-linked-ads/facebook-app-install-ads.md
    - Facebook Traffic and Conversion Ads: pages/deep-linked-ads/facebook-traffic-conversion-ads.md
    - Facebook Platform Ads: pages/deep-linked-ads/facebook-platform-ads.md
    - Facebook Dynamic Ads: pages/deep-linked-ads/facebook-dynamic-ads.md
    - V2 Event: pages/apps/v2event.md
    - People-Based Attribution: pages/dashboard/people-based-attribution.md
    - Enable Single Sign On: pages/dashboard/sso.md
    - Legacy Data Export API: pages/exports/api.md
    - Legacy Webhooks: pages/exports/webhooks.md
    - Event Ontology: pages/exports/event_ontology_data_schema.md
    - New Data Integrations: pages/integrations/faq.md
    - Facebook FAQ and Advanced Options: pages/deep-linked-ads/facebook-ads-faq.md
    - Access Level: pages/dashboard/access-level.md
    - Dynamic Product Feeds: pages/deep-linked-ads/dynamic-product-feeds.md
    - Tracking Link Parameters: pages/deep-linked-ads/url_params.md
    - Criteo: pages/deep-linked-ads/criteo.md
    - Branch Universal Ads: pages/deep-linked-ads/branch-universal-ads.md